In [ ]:
import pandas as pd
import numpy as np

# 2021 CLEANING
- loaded in 2021
- select the columns
- rename the columns
- clean the columns
- saved the clean 2021

In [77]:
# test print some of the columns
df_2021 = pd.read_csv("../data/raw/nyts2021.csv", low_memory=False)
df_2021.shape

(20413, 1334)

In [ ]:
# get only columns needed for analysis
cols_2021 = [
    "QN1", "QN2", "QN3",
    "QN133", "QN134",
    "QN135A", "QN135B", "QN135C", "QN135D",
    "QN135E", "QN135F", "QN135G", "QN135H",
    "QN136", "QN137",
    "QN138A", "QN138B", "QN138C", "QN138D", "QN138E", "QN138F", "QN138G",
    "QN9"
]

# save as subset
df_2021_small = df_2021[cols_2021].copy()
df_2021_small.head()

,QN1,QN2,QN3,QN133,QN134,QN135A,QN135B,QN135C,QN135D,QN135E,...,QN136,QN137,QN138A,QN138B,QN138C,QN138D,QN138E,QN138F,QN138G,QN9
0,3.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4.0,1.0,1.0,8.0,4.0,NaN,1.0,1.0,1.0,NaN,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
2,4.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,2.0,1.0,4.0,2.0,NaN,NaN,1.0,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
4,3.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
# rename the columns
df_2021_small = df_2021_small.rename(columns={
    "QN1": "age",
    "QN2": "sex",
    "QN3": "grade",
    "QN133": "sm_usage",
    "QN134": "sm_freq",
    "QN135A": "platform_fb", #facebook
    "QN135B": "platform_insta", #instagram
    "QN135C": "platform_sc", # snapchat
    "QN135D": "platform_tt", #tiktok
    "QN135E": "platform_twitter", #twitter
    "QN135F": "platform_reddit", #reddit
    "QN135G": "platform_yt", #youtube
    "QN135H": "platform_other", #other
    "QN136": "post_freq",
    "QN137": "interact_freq",
    "QN138A": "creator_real_life",
    "QN138B": "creator_online_friends",
    "QN138C": "creator_influencers",
    "QN138D": "creator_brands_sellers",
    "QN138E": "creator_news",
    "QN138F": "creator_public_health",
    "QN138G": "creator_other",
    "QN9": "usage" #target variable
})

# see the renamed dataset
df_2021_small.head()

,age,sex,grade,sm_usage,sm_freq,platform_fb,platform_insta,platform_sc,platform_tt,platform_twitter,...,post_freq,interact_freq,creator_real_life,creator_online_friends,creator_influencers,creator_brands_sellers,creator_news,creator_public_health,creator_other,usage
0,3.0,2.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,4.0,1.0,1.0,8.0,4.0,0.0,1.0,1.0,1.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN
2,4.0,2.0,1.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,4.0,2.0,1.0,4.0,2.0,0.0,0.0,1.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN
4,3.0,2.0,1.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [20]:
#look at values prior to cleaning
for col in df_2021_small.columns:
    print(f"\n{col}")
    print(df_2021_small[col].value_counts(dropna=False).sort_index().head(15))

# make sure all columns are numeric
df_2021_small = df_2021_small.apply(pd.to_numeric, errors="coerce")

# check the missing values before cleaning
df_2021_small.isna().sum()

age
age
1.0       34
2.0        4
3.0     1391
4.0     3204
5.0     3308
6.0     3079
7.0     2872
8.0     2562
9.0     2504
10.0    1208
11.0     178
NaN       69
Name: count, dtype: int64

sex
sex
1.0    10368
2.0     9919
NaN      126
Name: count, dtype: int64

grade
grade
1.0    3371
2.0    3198
3.0    3194
4.0    3097
5.0    2542
6.0    2595
7.0    2281
8.0      48
NaN      87
Name: count, dtype: int64

sm_usage
sm_usage
1.0    1666
2.0     531
3.0     300
4.0    1109
5.0    1135
6.0    3446
7.0    3661
8.0    6778
NaN    1787
Name: count, dtype: int64

sm_freq
sm_freq
1.0    4586
2.0    4469
3.0    2216
4.0    3241
5.0    2307
NaN    3594
Name: count, dtype: int64

platform_fb
platform_fb
0.0    18343
1.0     2070
Name: count, dtype: int64

platform_insta
platform_insta
0.0    13219
1.0     7194
Name: count, dtype: int64

platform_sc
platform_sc
0.0    13611
1.0     6802
Name: count, dtype: int64

platform_tt
platform_tt
0.0    12959
1.0     7454
Name: count, dtype: int64

platform_twitter
platform_twitter
0.0    18152
1.0     2261
Name: count, dtype: int64

platform_reddit
platform_reddit
0.0    19191
1.0     1222
Name: count, dtype: int64

platform_yt
platform_yt
0.0    13567
1.0     6846
Name: count, dtype: int64

platform_other
platform_other
0.0    19475
1.0      938
Name: count, dtype: int64

post_freq
post_freq
1.0    14310
2.0     1095
3.0      499
4.0      478
5.0      349
NaN     3682
Name: count, dtype: int64

interact_freq
interact_freq
1.0    12262
2.0     2464
3.0      773
4.0      737
5.0      430
NaN     3747
Name: count, dtype: int64

creator_real_life
creator_real_life
0.0    15874
1.0     4539
Name: count, dtype: int64

creator_online_friends
creator_online_friends
0.0    17614
1.0     2799
Name: count, dtype: int64

creator_influencers
creator_influencers
0.0    14347
1.0     6066
Name: count, dtype: int64

creator_brands_sellers
creator_brands_sellers
0.0    15122
1.0     5291
Name: count, dtype: int64

creator_news
creator_news
0.0    18309
1.0     2104
Name: count, dtype: int64

creator_public_health
creator_public_health
0.0    15012
1.0     5401
Name: count, dtype: int64

creator_other
creator_other
0.0    17782
1.0     2631
Name: count, dtype: int64

usage
usage
0.0     2154
1.0      286
2.0      138
3.0       82
4.0       52
5.0       80
6.0       21
7.0       23
8.0        9
9.0        8
10.0      73
11.0       4
12.0      12
13.0       6
14.0       8
Name: count, dtype: int64

age                          69
sex                         126
grade                        87
sm_usage                   1787
sm_freq                    3594
platform_fb                   0
platform_insta                0
platform_sc                   0
platform_tt                   0
platform_twitter              0
platform_reddit               0
platform_yt                   0
platform_other                0
post_freq                  3682
interact_freq              3747
creator_real_life             0
creator_online_friends        0
creator_influencers           0
creator_brands_sellers        0
creator_news                  0
creator_public_health         0
creator_other                 0
usage                     16823
dtype: int64

In [21]:
# fill in the multiselect binary columns: 1 = selected, 0 = not selected
binary_cols = [
    "platform_fb","platform_insta","platform_sc","platform_tt",
    "platform_twitter","platform_reddit","platform_yt","platform_other",
    "creator_real_life","creator_online_friends","creator_influencers",
    "creator_brands_sellers","creator_news","creator_public_health","creator_other"
]

df_2021_small[binary_cols] = df_2021_small[binary_cols].fillna(0)

# drop rows where the target variable is missing
df_2021_small = df_2021_small[df_2021_small["usage"].notna()].copy()

In [55]:
# make the target variable binary: 1 = current ecig user; 0 = no current use
df_2021_small["ecig_current"] = (df_2021_small["usage"] > 0).astype(int)

# median-impute remaining ordinal / demog columns
ordinal_cols = [
    "age", "sex", "grade",
    "sm_usage", "sm_freq",
    "post_freq", "interact_freq"
]

df_2021_small[ordinal_cols] = df_2021_small[ordinal_cols].fillna(
    df_2021_small[ordinal_cols].median()
)

# add in a year column# add year column
df_2021_small["year"] = 2021
df_2021_small["platform_twitch"] = 0 # twitch was not included in 2021 survey so we are adding it here
df_2021_small.isna().sum() # extra missing value check

age                       0
sex                       0
grade                     0
sm_usage                  0
sm_freq                   0
platform_fb               0
platform_insta            0
platform_sc               0
platform_tt               0
platform_twitter          0
platform_reddit           0
platform_yt               0
platform_other            0
post_freq                 0
interact_freq             0
creator_real_life         0
creator_online_friends    0
creator_influencers       0
creator_brands_sellers    0
creator_news              0
creator_public_health     0
creator_other             0
usage                     0
ecig_current              0
year                      0
platform_twitch           0
dtype: int64

In [56]:
# target balance check
df_2021_small["ecig_current"].value_counts(normalize=True)

ecig_current
0    0.6
1    0.4
Name: proportion, dtype: float64

In [57]:
# preview final cleaned dataset
df_2021_small.head()

# save cleaned 2021 file
df_2021_small.to_csv("../data/cleaned/nyts2021_clean.csv", index=False)

# 2022 Cleaning
- load 2022
- select columns
- rename columns
- clean columns
- save cleaned 2022

In [58]:
# load in 2022 data
df_2022 = pd.read_csv("../data/raw/nyts2022.csv", low_memory=False)

# preview data
print(df_2022.shape)
df_2022.head()

(28291, 1334)

,newid,Location,QN1,QN2,QN3,QN4A,QN4B,QN4C,QN4D,QN4E,...,CBIDIS,CHTP,CPOUCH,psu,stratum,hsms,finwgt,v_stratum,v_stratum2,psu2
0,103102,NaN,4.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,...,2.0,2.0,2.0,30358,NaN,MS,4.192270,400,400,30358
1,103103,NaN,5.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,...,2.0,2.0,2.0,30358,NaN,MS,4.192270,400,400,30358
2,103104,NaN,4.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,...,2.0,2.0,2.0,30358,NaN,MS,5.992877,400,400,30358
3,103105,NaN,5.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,...,2.0,2.0,2.0,30358,NaN,MS,5.992877,400,400,30358
4,103106,NaN,5.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,30358,NaN,MS,5.992877,400,400,30358

In [ ]:
# select columns for analysis
cols_2022 = [
    "QN1","QN2","QN3",
    "QN133","QN134",
    "QN135A","QN135B","QN135C","QN135D",
    "QN135E","QN135F","QN135G","QN135H",
    "QN136","QN137",
    "QN138A","QN138B","QN138C","QN138D",
    "QN138E","QN138F","QN138G",
    "QN9"
]

df_2022_small = df_2022[cols_2022].copy()

In [61]:
# rename columns like 2021
df_2022_small = df_2022_small.rename(columns={
    "QN1":"age",
    "QN2":"sex",
    "QN3":"grade",
    "QN133":"sm_usage",
    "QN134":"sm_freq",

    "QN135A":"platform_fb",
    "QN135B":"platform_insta",
    "QN135C":"platform_sc",
    "QN135D":"platform_tt",
    "QN135E":"platform_twitter",
    "QN135F":"platform_reddit",
    "QN135G":"platform_yt",
    "QN135H":"platform_other",

    "QN136":"post_freq",
    "QN137":"interact_freq",

    "QN138A":"creator_real_life",
    "QN138B":"creator_online_friends",
    "QN138C":"creator_influencers",
    "QN138D":"creator_brands_sellers",
    "QN138E":"creator_news",
    "QN138F":"creator_public_health",
    "QN138G":"creator_other",

    "QN9":"usage"
})

# convert it all to numeric
df_2022_small = df_2022_small.apply(pd.to_numeric, errors="coerce")

# fill binary columns like 2021
binary_cols = [
    "platform_fb","platform_insta","platform_sc","platform_tt",
    "platform_twitter","platform_reddit","platform_yt","platform_other",
    "creator_real_life","creator_online_friends","creator_influencers",
    "creator_brands_sellers","creator_news","creator_public_health","creator_other"
]

df_2022_small[binary_cols] = df_2022_small[binary_cols].fillna(0)

# remove rows w/o the target
df_2022_small = df_2022_small[df_2022_small["usage"].notna()].copy()

# make the target binary 
df_2022_small["ecig_current"] = (df_2022_small["usage"] > 0).astype(int)

# median impute ordinal cols
ordinal_cols = [
    "age","sex","grade",
    "sm_usage","sm_freq",
    "post_freq","interact_freq"
]

df_2022_small[ordinal_cols] = df_2022_small[ordinal_cols].fillna(
    df_2022_small[ordinal_cols].median()
)

# add in year column
df_2022_small["year"] = 2022
df_2022_small["platform_twitch"] = 0
df_2022_small.isna().sum() # check dataset again for missing values

age                       0
sex                       0
grade                     0
sm_usage                  0
sm_freq                   0
platform_fb               0
platform_insta            0
platform_sc               0
platform_tt               0
platform_twitter          0
platform_reddit           0
platform_yt               0
platform_other            0
post_freq                 0
interact_freq             0
creator_real_life         0
creator_online_friends    0
creator_influencers       0
creator_brands_sellers    0
creator_news              0
creator_public_health     0
creator_other             0
usage                     0
ecig_current              0
year                      0
platform_twitch           0
dtype: int64

In [62]:
df_2022_small.head() # preview

,age,sex,grade,sm_usage,sm_freq,platform_fb,platform_insta,platform_sc,platform_tt,platform_twitter,...,creator_online_friends,creator_influencers,creator_brands_sellers,creator_news,creator_public_health,creator_other,usage,ecig_current,year,platform_twitch
4,5.0,1.0,2.0,7.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,30.0,1,2022,0
6,6.0,2.0,4.0,8.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,2022,0
9,5.0,1.0,2.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1,2022,0
14,8.0,2.0,6.0,8.0,5.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,2022,0
16,4.0,2.0,1.0,2.0,4.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,20.0,1,2022,0

In [63]:
# save cleaned 2022 dataset
df_2022_small.to_csv("../data/cleaned/nyts2022_clean.csv", index=False)

# 2023 Cleaning
- load 2023
- select columns
- rename columns
- clean columns
- save cleaned 2023

In [ ]:
# load 2023 raw data
df_2023 = pd.read_csv("../data/raw/nyts2023.csv", low_memory=False)
# test check
print(df_2023.shape)

(22069, 1469)

In [67]:
# get necessary columns (different for 2023)
cols_2023 = [
    "QN1","QN2","QN3",
    "QN121","QN122",
    "QN123a","QN123b","QN123c","QN123d",
    "QN123e","QN123f","QN123g","QN123h","QN123i",
    "QN124","QN125",
    "QN126a","QN126b","QN126c","QN126d","QN126e","QN126f","QN126g",
    "QN9"
]

df_2023_small = df_2023[cols_2023].copy()

In [74]:
# rename the columns
df_2023_small = df_2023_small.rename(columns={

    "QN1":"age",
    "QN2":"sex",
    "QN3":"grade",

    "QN121":"sm_usage",
    "QN122":"sm_freq",

    "QN123a":"platform_fb",
    "QN123b":"platform_insta",
    "QN123c":"platform_sc",
    "QN123d":"platform_tt",
    "QN123e":"platform_twitch", # adding in twitch because it was included in 2023
    "QN123f":"platform_twitter",
    "QN123g":"platform_reddit",
    "QN123h":"platform_yt",
    "QN123i":"platform_other",

    "QN124":"post_freq",
    "QN125":"interact_freq",

    "QN126a":"creator_real_life",
    "QN126b":"creator_online_friends",
    "QN126c":"creator_influencers",
    "QN126d":"creator_brands_sellers",
    "QN126e":"creator_news",
    "QN126f":"creator_public_health",
    "QN126g":"creator_other",

    "QN9":"usage"
})

# convert to numeric
df_2023_small = df_2023_small.apply(pd.to_numeric, errors="coerce")

# fill binary cols
binary_cols = [
    "platform_fb","platform_insta","platform_sc","platform_tt",
    "platform_twitch","platform_twitter","platform_reddit",
    "platform_yt","platform_other",
    "creator_real_life","creator_online_friends","creator_influencers",
    "creator_brands_sellers","creator_news","creator_public_health","creator_other"
]

df_2023_small[binary_cols] = df_2023_small[binary_cols].fillna(0)

# drop missing target variable
df_2023_small = df_2023_small[df_2023_small["usage"].notna()].copy()
# create binary target 1/0
df_2023_small["ecig_current"] = (df_2023_small["usage"] > 0).astype(int)

# median imputation
ordinal_cols = [
    "age","sex","grade",
    "sm_usage","sm_freq",
    "post_freq","interact_freq"
]

df_2023_small[ordinal_cols] = df_2023_small[ordinal_cols].fillna(
    df_2023_small[ordinal_cols].median()
)

# add year column
df_2023_small["year"] = 2023

# double check no missing values
df_2023_small.isna().sum()

age                       0
sex                       0
grade                     0
sm_usage                  0
sm_freq                   0
platform_fb               0
platform_insta            0
platform_sc               0
platform_tt               0
platform_twitch           0
platform_twitter          0
platform_reddit           0
platform_yt               0
platform_other            0
post_freq                 0
interact_freq             0
creator_real_life         0
creator_online_friends    0
creator_influencers       0
creator_brands_sellers    0
creator_news              0
creator_public_health     0
creator_other             0
usage                     0
ecig_current              0
year                      0
dtype: int64

In [ ]:
df_2023_small.head() # preview dataset

,age,sex,grade,sm_usage,sm_freq,platform_fb,platform_insta,platform_sc,platform_tt,platform_twitch,...,creator_real_life,creator_online_friends,creator_influencers,creator_brands_sellers,creator_news,creator_public_health,creator_other,usage,ecig_current,year
0,5.0,2.0,2.0,7.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,2023
1,8.0,2.0,1.0,7.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1,2023
2,5.0,1.0,2.0,7.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,2023
3,4.0,2.0,2.0,7.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,1,2023
4,4.0,2.0,1.0,6.0,5.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,2023

In [76]:
# save cleaned 2023 dataset
df_2023_small.to_csv("../data/cleaned/nyts2023_clean.csv", index=False)

# Merge Cleaned NYTS Datasets (2021-2023)

In [ ]:
# load in cleaned datasets
df_2021_clean = pd.read_csv("../data/cleaned/nyts2021_clean.csv")
df_2022_clean = pd.read_csv("../data/cleaned/nyts2022_clean.csv")
df_2023_clean = pd.read_csv("../data/cleaned/nyts2023_clean.csv")

# add in order so it's same across all datasets
cols_order = [
    "age","sex","grade",
    "sm_usage","sm_freq",
    "platform_fb","platform_insta","platform_sc","platform_tt",
    "platform_twitch",
    "platform_twitter","platform_reddit","platform_yt","platform_other",
    "post_freq","interact_freq",
    "creator_real_life","creator_online_friends","creator_influencers",
    "creator_brands_sellers","creator_news","creator_public_health","creator_other",
    "usage","ecig_current","year"
]

df_2021_clean = df_2021_clean[cols_order]
df_2022_clean = df_2022_clean[cols_order]
df_2023_clean = df_2023_clean[cols_order]

# double check shape
print(df_2021_clean.shape)
print(df_2022_clean.shape)
print(df_2023_clean.shape)

(3590, 26)
(5720, 26)
(3278, 26)

In [83]:
# double checking column names
print(df_2021_clean.columns)
print(df_2022_clean.columns)
print(df_2023_clean.columns)

Index(['age', 'sex', 'grade', 'sm_usage', 'sm_freq', 'platform_fb',
       'platform_insta', 'platform_sc', 'platform_tt', 'platform_twitch',
       'platform_twitter', 'platform_reddit', 'platform_yt', 'platform_other',
       'post_freq', 'interact_freq', 'creator_real_life',
       'creator_online_friends', 'creator_influencers',
       'creator_brands_sellers', 'creator_news', 'creator_public_health',
       'creator_other', 'usage', 'ecig_current', 'year'],
      dtype='object')
Index(['age', 'sex', 'grade', 'sm_usage', 'sm_freq', 'platform_fb',
       'platform_insta', 'platform_sc', 'platform_tt', 'platform_twitch',
       'platform_twitter', 'platform_reddit', 'platform_yt', 'platform_other',
       'post_freq', 'interact_freq', 'creator_real_life',
       'creator_online_friends', 'creator_influencers',
       'creator_brands_sellers', 'creator_news', 'creator_public_health',
       'creator_other', 'usage', 'ecig_current', 'year'],
      dtype='object')
Index(['age', 'sex', 'grade', 'sm_usage', 'sm_freq', 'platform_fb',
       'platform_insta', 'platform_sc', 'platform_tt', 'platform_twitch',
       'platform_twitter', 'platform_reddit', 'platform_yt', 'platform_other',
       'post_freq', 'interact_freq', 'creator_real_life',
       'creator_online_friends', 'creator_influencers',
       'creator_brands_sellers', 'creator_news', 'creator_public_health',
       'creator_other', 'usage', 'ecig_current', 'year'],
      dtype='object')

In [ ]:
# run the merge
df_all = pd.concat(
    [df_2021_clean, df_2022_clean, df_2023_clean],
    ignore_index=True
)

df_all.shape # check shape (3590 +5720 +3278 = 12588)

(12588, 26)

In [ ]:
df_all["year"].value_counts() # check year distribution

year
2022    5720
2021    3590
2023    3278
Name: count, dtype: int64

In [ ]:
df_all.isna().sum().sum() # missing value check

np.int64(0)

In [92]:
# save clean dataset concatinating 2021-2023!!!!
df_all.to_csv("../data/cleaned/nyts_2021_2023_clean.csv", index=False)

In [ ]:
df_all["ecig_current"].value_counts(normalize=True)

year
2021    0.400000
2022    0.472203
2023    0.477425
Name: ecig_current, dtype: float64

In [ ]:
df_all.groupby("year")["ecig_current"].mean() # youth vaping rate per year

year
2021    0.400000
2022    0.472203
2023    0.477425
Name: ecig_current, dtype: float64